### ISSUE TITLE
The InputSystem package has XR related errors - "The name 'XRController' does not exist in the current context."

### ISSUE THREAD

**Issue by jackpr-unity** [StayTalm/InputSystem#2]
With the latest xr/sdk/input-subsystem/develop katana build and this latest github, I get an error from the FunctionalTests.cs when I switch the platform to WindowsMR.

Sounds like this functionality got renamed, and that rename was not reflected in the most recent commit.

![capture](https://user-images.githubusercontent.com/36174025/38214730-65c27f2c-367a-11e8-8b20-acd4630915c6.PNG)

**Comment by jackpr-unity** [comment]
Does this mean that the InputSystem package has a dependency on the XR-specific stuff?  If so, the InputSystem package should not have this dependency.

**Comment by jackpr-unity** [comment]
Changing name to reflect that this seems platform independent.

**Comment by jackpr-unity** [comment]
commit 30011e3f95c11c406461c2bae2d94237396c70c4 fixed this issue.

**Comment by jackpr-unity** [comment]
Nope, issue is back :-(

**Comment by jackpr-unity** [comment]
I tried re-pulling the develop branch fresh, and this issue still exists.

**Comment by StayTalm** [comment]
This has been fixed on both develop and master branches as of changeset: https://github.com/StayTalm/InputSystem/commit/16f9c6d9ba22669e74dc0a72c9bbc683cbd2aee3
