### ISSUE TITLE
208 errors when the editor is opened with WMR

### ISSUE THREAD

**Issue by jackpr-unity** [StayTalm/InputSystem#21]
Editor commit d14c582ddb20
Github master 52e9f02

Console output:
Unity extensions are not yet initialized, so we cannot say if the 'D:/UnityEditors/Versions/branch_xr_sdk_input-subsystem_2018-05-01/Data/UnityExtensions/Unity/UnitySpatialTracking/Runtime/UnityEngine.SpatialTracking.dll' is compatible with platform WindowsStoreApps
UnityEditorInternal.InternalEditorUtility:GetPrecompiledAssemblies(Boolean, BuildTargetGroup, BuildTarget)
UnityEditorInternal.InternalEditorUtility:GetMonoIslandsForPlayer() (at C:/buildslave/unity/build/Editor/Mono/InternalEditorUtility.cs:395)
System.Reflection.MethodBase:Invoke(Object, Object[])
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit:CompilationUnits(String)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit:CompilationUnitsForPlayer()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder:CreatePlayerProject(CompilationUnit)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder:CreateSolution()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder:CreateSolutionFromAssetDatabase()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator:GenerateProject()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilePostprocessor:OnPreGeneratingCSProjectFiles()
UnityEditor.Modules.ModuleManager:RegisterAdditionalUnityExtensions()

**Comment by StayTalm** [comment]
This looks to be a universal issue, and not something related to XR Input.
