### ISSUE TITLE
Oculus Rift remote is not supported

### ISSUE THREAD

**Issue by jackpr-unity** [StayTalm/InputSystem#29]

**Comment by jackpr-unity** [comment]
As of 0.0.2-preview it shows up as a XRController, so that's good.

It does a decent job of mapping.  However it maps the "select" button in the center to "start."  Should this map to "PrimaryButton" instead?

**Comment by jackpr-unity** [comment]
As of 0.0.4-preview and Trunk build 3e681eca9b01 (16 July 16) the remote does not appear as a supported device.

**Comment by jackpr-unity** [comment]
As of 0.0.4-preview and Trunk build 3e681eca9b01 (16 July 16) - same status

**Comment by Dianna3D** [comment]
Issue migrated to package repository: https://github.com/Unity-Technologies/InputSystem/issues/205
