### ISSUE TITLE
OpenVR Vive devices are duplicated every time playmode is entered

### ISSUE THREAD

**Issue by jackpr-unity** [StayTalm/InputSystem#3]
Pressing play in the editor adds OpenVR Vive devices correctly.  When exiting playmode, the devices stick around in the InputSystem devices list.  Every subsequent time playmode is entered, duplicate Vive devices are added.

**Comment by jackpr-unity** [comment]
Hm, I'm not sure what is triggering this.  It was happening reliably earlier, now it isn't happening at all.  I will update when I have more information on how to reproduce the issue.

**Comment by jackpr-unity** [comment]
As of this posting, I am observing this same issue with Oculus TrackingReferences

**Comment by StayTalm** [comment]
I believe this is corrected.  I've not seen this in weeks.
