### ISSUE TITLE
Vive Controllers don't cast as XRControllerWithRumble

### ISSUE THREAD

**Issue by jackpr-unity** [StayTalm/InputSystem#4]
I tried using the rumble code you sent me, and it appears that this line doesn't work correctly for Vive Controllers:
XRControllerWithRumble rightHandController = XRController.rightHand as XRControllerWithRumble;

**Comment by jackpr-unity** [comment]
The Rift controllers work as expected.

**Comment by StayTalm** [comment]
The now cast properly as having rumble, but they won't yet rumble until some minor native changes make it to trunk, so I'll keep this open until then.

**Comment by jackpr-unity** [comment]
Migrating issue to package repository: https://github.com/Unity-Technologies/InputSystem/issues/200
